### ISSUE TITLE
filename is incorrect for unigram

### ISSUE THREAD

**Issue by Sebek05** [rondevous/stringnames#1]
Hi friend, can you rewrite your web script to generate correct names for Unigram files?

**Comment by rondevous** [comment]
Yes, but always remember that no matter which language file you use to generate the stringnames, whether it english (with 2 plural rules) or arabic (with 6 plural rules), the stringnames will always be generated. Even if the file name is the same.

I hope there is nothing else wrong with the web script. Its just the output name, yes.
I will fix the naming, but in order to make it somewhat future-proof, I have few questions:
1. Will you always use the English language files to generate the stringnames?
2. What about using a language that supports all 6 plural rules like arabic or welsh? that way it covers all possible stringnames... except... (a) there's no welsh translation and (b) most people don't know how to type and search arabic letters.

For (2), I have gone through through official list of telegram android languages and checked if any readable ASCII languages have all 6 plural rules... but got none. (highest was Polish language which has 4 plural rules). 
If you know any beta-languages that any english-speaking person can type, please advise. Accordingly I will make a provision to rename the filename correctly.

**Comment by rondevous** [comment]
For now, i will rename only the english filename properly. and if any other language is used, i will just append _stringnames at the end of the file.

e.g: `unigram_en_v645334.xml` will rename to `unigram_stringnames.xml`
but `unigram_cy_v645334.xml` will rename to `unigram_cy_v645334_stringnames.xml`
